### ISSUE TITLE
tts.cloud_say - Stopped working

### ISSUE THREAD

**Issue by BigEfromDaBx** [cgarwood/homeassistant-fullykiosk#96] opened 2022-05-05 19:08 UTC
All of a sudden when I run the command below.  I get no audio from my fire7.  My fire7 gives me a little popup window saying "failed loading sound: Wrong URL or unsupported format?" when I run it.  

I get no error when running it from HA on the developer tab and get a green checkmark stating it was successfully run.

`service: tts.cloud_say
data:
  message: this is a test
  entity_id: media_player.fire_tablet_media_player`

**Comment by ingo01978** [comment] 2022-05-07 15:16
+1 on this issue.

**Comment by ukgaz1987** [comment] 2022-05-07 15:40
I'm getting the same issue since updating to 2022.5. Have tried as much as I can think of but in the end, rolling back to 2022.4.7 was the only fix for me.

**Comment by frver** [comment] 2022-05-07 16:48
I have the same issue as BigEfromDaBx. I can confirm when rolling back to 2022.4.7 it works normally again. Thanks for the hint ukgaz1987 !

**Comment by NvrFollow** [comment] 2022-05-08 03:03
+1 on this issue.

**Comment by jdbrookes** [comment] 2022-05-08 08:20
Seeing the same here on 2022.5 - The network settings have been reorganised in this version but when I check Settings -> System -> Network I already have my Internet and Local Network details set correctly.

TTS with my Google Home devices is working ok.

**Comment by fabiobrolo** [comment] 2022-05-12 00:16
+1 on this issue

**Comment by big23** [comment] 2022-05-12 09:28
+1 on this issue.

**Comment by Misak** [comment] 2022-05-12 11:14
+1

**Comment by Jizzay1** [comment] 2022-05-12 21:50
+1

**Comment by pvillanyi** [comment] 2022-05-15 17:36
After updating HA to 2022.5 my TTS notifications stopped also. I see no error on HA log, but the Kiosk Tablet pops the message "wrong URL or unsupported format"
Since I can send TTS message to the Tablet over browser with ?cmd there must be something wrong in the integration.
Could you look into it why HA is sending the command to Fully in a wrong format recently?

**Comment by cgarwood** [comment] 2022-05-15 19:02
Sorry for the delay, was swamped earlier in the week and sick the later part of the week. Working on a patch...

**Comment by cgarwood** [comment] 2022-05-15 21:13
Should be fixed by https://github.com/cgarwood/homeassistant-fullykiosk/pull/99 - will prepare a release soon

**Closed** 2022-05-15 21:13 UTC
